# Generated by Django 2.0.3 on 2018-05-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starttest',
            name='user',
        ),
    ]
