# Generated by Django 2.0.3 on 2018-05-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_starttest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='idQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.TextQuestion', verbose_name='id вопроса'),
        ),
        migrations.AddField(
            model_name='starttest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Кто проходит'),
        ),
    ]
