# Generated by Django 2.0.3 on 2018-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сategorie', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Сессия'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователь'},
        ),
    ]
