# Generated by Django 2.0.3 on 2018-03-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180322_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='GropUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gropUser', models.CharField(max_length=255, verbose_name='Группа пользователей')),
            ],
            options={
                'verbose_name_plural': 'Группа пользователей',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('dateStart', models.DateTimeField(verbose_name='Начало теста')),
                ('dateEnd', models.DateTimeField(verbose_name='Окончание теста')),
                ('gropUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GropUser', verbose_name='Группа пользователей')),
                ('сategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(verbose_name='Время сессии'),
        ),
    ]
