# Generated by Django 2.0.3 on 2018-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180322_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Тест'},
        ),
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(default='as', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='as', max_length=255, verbose_name='Фамилия'),
        ),
    ]
