# Generated by Django 2.0.3 on 2018-04-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180408_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
