# Generated by Django 2.0.3 on 2018-04-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180408_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='сategorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Categorie', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.CharField(default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
