# Generated by Django 2.0.3 on 2018-04-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180419_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=None, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='сategorie',
            field=models.CharField(default=None, max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='gropuser',
            name='gropUser',
            field=models.CharField(default=None, max_length=255, verbose_name='Группа пользователей'),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=None, verbose_name='Время сессии'),
        ),
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(default=None, max_length=255, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='test',
            name='dateEnd',
            field=models.DateTimeField(default=None, verbose_name='Окончание теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='dateStart',
            field=models.DateTimeField(default=None, verbose_name='Начало теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='gropUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.GropUser', verbose_name='Группа пользователей'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='сategorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Categorie', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default=None, max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=255, verbose_name='Пароль'),
        ),
    ]
