# Generated by Django 2.0.3 on 2018-04-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180408_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='сategorie',
        ),
        migrations.AddField(
            model_name='user',
            name='gropUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.GropUser', verbose_name='Группа пользователей'),
        ),
    ]
