# Generated by Django 2.0.3 on 2018-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180408_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='qwerty@qwe.com', max_length=255, verbose_name='email'),
        ),
    ]
