# Generated by Django 2.0.3 on 2018-05-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180425_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None, verbose_name='Ответ')),
                ('boolean', models.BooleanField(default=None, verbose_name='Правильно')),
            ],
            options={
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textQuestion', models.TextField(default=None, verbose_name='Текст вопроса')),
                ('typeQuestion', models.CharField(default=None, max_length=10, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name_plural': 'Текст вопроса',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='dateEnd',
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='test',
            name='colQuition',
            field=models.IntegerField(default=None, verbose_name='Количество вопросов'),
        ),
        migrations.AddField(
            model_name='test',
            name='fullInfo',
            field=models.TextField(default=None, verbose_name='Полная информация'),
        ),
        migrations.AddField(
            model_name='test',
            name='shortInfo',
            field=models.TextField(default=None, verbose_name='Краткая информация'),
        ),
        migrations.AddField(
            model_name='test',
            name='timeTest',
            field=models.IntegerField(default=None, verbose_name='Время на прохождение'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.TextQuestion', verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Test', verbose_name='Тест'),
        ),
    ]
