# Generated by Django 2.0.3 on 2018-04-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='dateEnd',
        ),
        migrations.RemoveField(
            model_name='test',
            name='dateStart',
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Группа пользователей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='birth',
            field=models.DateTimeField(default=1, verbose_name='Создание теста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='colQuestion',
            field=models.IntegerField(default=1, verbose_name='Колличество вопросов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='fullData',
            field=models.TextField(default=1, verbose_name='Полная информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Колличество прохождений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='shortData',
            field=models.TextField(default=1, verbose_name='Краткая информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=1, verbose_name='Время теста'),
            preserve_default=False,
        ),
    ]
