# Generated by Django 2.0.3 on 2018-04-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_test_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='test',
            name='colQuestion',
        ),
        migrations.RemoveField(
            model_name='test',
            name='fullData',
        ),
        migrations.RemoveField(
            model_name='test',
            name='gropUser',
        ),
        migrations.RemoveField(
            model_name='test',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='test',
            name='shortData',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
    ]
