# Generated by Django 2.0.3 on 2018-04-09 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180409_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='birth',
            field=models.DateTimeField(blank=True, default=1, verbose_name='Создание теста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='colQuestion',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now, verbose_name='Колличество вопросов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='fullData',
            field=models.TextField(blank=True, verbose_name='Полная информация'),
        ),
        migrations.AddField(
            model_name='test',
            name='gropUser',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.GropUser', verbose_name='Группа пользователей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='quantity',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now, verbose_name='Колличество прохождений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='shortData',
            field=models.TextField(blank=True, verbose_name='Краткая информация'),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now, verbose_name='Время теста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='сategorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categorie', verbose_name='Категория'),
        ),
    ]
