# Generated by Django 2.0.3 on 2018-04-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180409_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='gropUser',
        ),
        migrations.RemoveField(
            model_name='test',
            name='сategorie',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
